### ISSUE TITLE
I cant create a method to the field "Data_Nasc"

### ISSUE THREAD

**Issue by Soufraz** [robclancy/presenter#39]
I have a field in my clients table, called "Data_Nasc".
But, I cant create a method to presenter this field in ClientePresenter.
I get it that when the field have underline, I need remove the underline and create the presenter method in came on case. 
But, in this specific case? Data_Nasc. What I can do to workaround this?

**Comment by robclancy** [comment]
You can override this method to add support for what you need. 
https://github.com/robclancy/presenter/blob/master/src/Presenter.php#L214

Sorry for the extremely late reply, github hasn't been sending me emails for some reason, should be all sorted now.
