### ISSUE TITLE
Is this going to be updated for Laravel 5?

### ISSUE THREAD

**Issue by stepquick** [robclancy/presenter#42]
More curious than anything @robclancy? I noticed that there are pull requests for it, but nothing has been merged.

**Comment by robclancy** [comment]
I wasn't aware of any issue as I don't really use this anymore since I work on single page applications. The PRs I have open aren't related to Laravel 5. If you use and find an issue report it and I'll get it fixed.

**Comment by stepquick** [comment]
Ah gotcha. https://github.com/robclancy/presenter/pull/40 This pull would probably fix the error that presenter gives when trying to run composer update.

**Comment by robclancy** [comment]
Oh, I never noticed those. It used to always make an issue for pull requests on here? I'll just merge it I guess.

**Comment by stepquick** [comment]
Cool that was my only issue. Thanks.
