### ISSUE TITLE
Running with view composers

### ISSUE THREAD

**Issue by Torann** [robclancy/presenter#44]
Is it not possible to use this presenter with [Laravel View Composers](http://laravel.com/docs/5.1/views#view-composers)? If I add the `Robbo\Presenter\PresenterServiceProvider::class,` service in my `config/app.php` file I keep getting an undefined variable error (where the variable is set using the view composer). When presenter service is commented out the composers work fine.

**Running**
- Laravel v5.1
- robclancy/presenter v1.3.1

**Comment by robclancy** [comment]
Can you give the full error?

**Comment by Torann** [comment]
I can't, sorry. I'm no longer using "robclancy/presenter" in any of my projects.
