### ISSUE TITLE
Does Laravel 5.1 work?

### ISSUE THREAD

**Issue by goodspb** [robclancy/presenter#46]
I used presenter in my laravel 4.2 project , but these day I want to upgrade my project to L5.1 .  I also found that your commit common say something about L5, is that means you had upgrade presenter ?

**Comment by robclancy** [comment]
I have run tests fine but I haven't yet used this on a L5 project so I am not sure if it works. I am really low on time so haven't been able to do anything.

I also plan to write up some blog posts as I believe that native traits will be a better fit for presenters than this library.
