### ISSUE TITLE
PHP 8.2 warnings

### ISSUE THREAD

**Issue by benjamin-hmc** [robclancy/presenter#66]
Hi, we recently updated our Laravel project to Laravel 10 and PHP8.2 and we are now getting the following warnings:

- Return type of Robbo\Presenter\Presenter::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/app/current/vendor/robclancy/presenter/src/Presenter.php on line 124
- Return type of Robbo\Presenter\Presenter::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/app/current/vendor/robclancy/presenter/src/Presenter.php on line 108
- Return type of Robbo\Presenter\Presenter::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/app/current/vendor/robclancy/presenter/src/Presenter.php on line 97
- Return type of Robbo\Presenter\Presenter::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/app/current/vendor/robclancy/presenter/src/Presenter.php on line 75

Nothing critical but would be great if they got fixed :)

**Comment by robclancy** [comment]
It turns out I already fixed this but I have somehow messed up releases a bunch. I think I was meant to do a 3.0 with PHP 8.1 minimum.
